### ISSUE TITLE
Reference SVG file

### ISSUE THREAD

**Issue by turbobabr** [xsrf/easyeda-svg-import#1]
Do you have any reference SVG file that 100% works with the script? I'm trying to wrap my head around the script you'd developed(thank you very my for the job've done btw) and I can't make it working even with `SVG` files containing only path based primitives. 

It would be really nice to get some working ref examples in the repo.

**Comment by xsrf** [comment]
Good point, forgot about that. I've added one.
Feel free to open a new issue with a specific SVG that doesn't work.

**Comment by turbobabr** [comment]
Holymoly! It works!!! :)

![image](https://user-images.githubusercontent.com/6356526/97602569-6cc7d300-1a46-11eb-97e4-2c766d033a4a.png)

Thank you very much! Will investigate a bit further to figure out what's wrong with my designs! 👏

**Comment by xsrf** [comment]
Feel free to open an issue and I'll have a look. I want to support as many designs as possible. Just make sure your svg uses path-Tags (other primitives are not yet supported) and no (A)rc-Commands within the path. They won't work for now.
Maybe the path-Tag is not even parsed correctly. I've used regex to extract the `<path ... d="...">` Tags, not a proper XML parser ;)
