### ISSUE TITLE
Message: N items successfully imported

### ISSUE THREAD

**Issue by OpenSourceModular** [xsrf/easyeda-svg-import#14]
Andreas,
This is not an issue, but instead a feature request and a minor bug (I think).

It would be great if a message pops up after import that says something like "25 items successfully imported".

Also, it could be just me, but lets say I select a filename "PCB_Graphics.svg". 
I import it, and realized I messed up.
I go back and make changes to the file in inkscape and save it.
Now I go back and reload that same file. The changes do not appear. It is like it is not re-loading the new file.
If I resave it in inkscape with a new name, and then import it again, I get the changes.

The new screenshot looks great.

Thanks!

Justin

**Comment by xsrf** [comment]
Hey,
I think a short notification is a good idea. I'll add one with the next changes.

Regarding you're issue though: You have to reopen your file with `Load file ...` after every change. This is how loading files in Browsers works, it doesn't keep an open handle to your file on the disk. There is nothing I can do about it...

**Comment by OpenSourceModular** [comment]
Thanks!
