### ISSUE TITLE
custom pad shape 

### ISSUE THREAD

**Issue by MattKuebrich** [xsrf/easyeda-svg-import#18]
I'm trying to use svg-import to create a custom pad shape. I import an .svg as a "solid region" and then right-click and "Convert to Pad". It works, but when I add this footprint in a PCB, it's superrr slow and locks up for seconds at a time, making it pretty impossible to work with. Any ideas? Thanks!

**Comment by xsrf** [comment]
can you share the SVG and the footprints name you created?

**Comment by MattKuebrich** [comment]
After more investigation this morning, it seems to be locking up when my newly created pad passes over another pad or the board outline, which happens a lot when you're arranging components on the PCB. So I tried turning off "Realtime DRC" and that helps with it!

I've attached a zip file with my SVG file and an easyeda PCB json file. The PCB is just the pad I created and some resistors to show the problem. The pad is supposed to be a big touch sensor thing. If you drag the pad over the resistors or outside the board outline, you'll see it lock up if Realtime DRC is on. 

Thanks for your help!

[BLOB.zip](https://github.com/xsrf/easyeda-svg-import/files/6740683/BLOB.zip)

**Comment by xsrf** [comment]
Hey,
sorry that I didn't respond, but I'm closing this now.
You've identified that Realtime DRC together with a complex Pad-Shape causes the issue and disabling Realtime DRC is a workaround for that. I can't solve the issue, as it is an issue with EasyEDA, not the import. The Import works fine. How EasyEDA handles the imported shape is out of my control.
