### ISSUE TITLE
Extension not appearing in Browser mode

### ISSUE THREAD

**Issue by Nhouse111** [xsrf/easyeda-svg-import#20]
Hello. 
I'm using Chrome Version 95.0.4638.69 and Firefox Version 82.0  and after loading the extension, this doesn't appear on the top as used to do.
Unfortunately the extension doesn't Run on my desktop Version.

Do you have the same issue or can i do something to fix it? Thanks.

**Comment by Nhouse111** [comment]
Correction: I just noticed that on Desktop version 6.4.25 (6.4.25) is now working! (never worked before. quite weired) but still not working on web Easyeda designer (and time ago this was the only working option for me..)

**Comment by xsrf** [comment]
I'm currently on Chrome 96.0.4664.45 (64-Bit) and 1.8 works fine for me in EasyEDA 6.4.25.
Did the extension just vanish, or y did you install it again? Do you get any errors in the dev console (hit F12) in EasyEDA after loading the extension?

**Comment by Nhouse111** [comment]
I removed the extension and loaded it again and is working flawlessy now! no errors anymore and SVG import tab appears both in Desktop and in Web version!
