### ISSUE TITLE
When importing SVG onto bottom silk later it doesn't flip it

### ISSUE THREAD

**Issue by evrenucar** [xsrf/easyeda-svg-import#25]
When importing SVG onto bottom silk later it doesn't flip it
![bottom_layer_silk](https://user-images.githubusercontent.com/34896403/186971626-cec6b535-f28e-4731-a5a0-958a251d2170.png)

**Comment by xsrf** [comment]
Hmm, that's correct and that was actually intended for my use-case (images that shine through the PCB and thus need aligned masks on top and bottom). 

You can always select the imported items and uses EasyEDAs `Flip Horizontal` option though.

Do you think I should add `Flip Horizontal` option to the import?
Or an option to flip automatically when importing to bottom layers? 🤔

**Comment by evrenucar** [comment]
Almost 5 minutes after I opened the issue I figured out  how to **Flip Horizontally** in EasyEDA. I think it would be more intuitive to have graphics flipped automatically when importing to the bottom silk layer. However I don't think it is a must.

I fooled around for almost an hour before I came across your extension. It works great ^^
